### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cwmoriarty**
Clarifying use and fixing typo

### CODE REVIEW

**Comment by atsushieno** [comment]
The README already says "Everything is still subject to changes. Do not expect it as a stable synth plugin yet."

**Comment by cwmoriarty** [comment]
Thanks for consideration. My PR clarifies how to install this, it's unclear I'd need to clone it outside an existing ADLplug. 

And `patch` is mispelled.

**Comment by atsushieno** [comment]
Oh, ADLplug is registered as git submodule. If you run `git submodule update --init --recursive` you will see it checked out. Sorry, but it is a generic git repository structure that I don't think I have to add it to README. Maybe in the future, but not right now.

**Comment by cwmoriarty** [comment]
Yup, I just missed that at first!

Great project, BTW. I want to get ADLplug built for my M1 Mac and this is a big step toward that goal.

**Comment by atsushieno** [comment]
It is 99.9% on top of jpcima's great work but thank you anyway! And yes building on M1 was my need too.

**Comment by cwmoriarty** [comment]
@atsushieno do you happen to have any M1/ARM builds you could upload as a Release here? 

I don't have a pre-macos 15.x machine handy and I'm running up against [JUCE/issues/1414](https://github.com/juce-framework/JUCE/issues/1414). Thanks.

**Comment by atsushieno** [comment]
I cannot sign my binaries, my Apple ID is inaccessible due to WTF reason Apple made on their secret questions (kinda well known problem). You can resort to GitHub Actions macos-14 server (fork this repo, and add your actions setup). I can try to set up it but I'll be quite busy this week so do not expect that to happen for a while...

**Pull request closed without merging**
